<?php
$z[0]=Array("field","",262,281);
$z[0][4]['name']="title";
$z[1]=Array("global","",282,308);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",353,375);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",419,470);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",865,900);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1291,1320);
$z[5][4]['name']="position";
$z[6]=Array("arclist","\r\n                    <dd><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a></dd>\r\n                    ",1547,1743);
$z[6][4]['flag']="c";
$z[6][4]['titlelen']="42";
$z[6][4]['row']="5";
$z[7]=Array("arclist","\r\n                    <dd><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a></dd>\r\n                    ",1957,2146);
$z[7][4]['row']="5";
$z[7][4]['orderby']="click";
$z[8]=Array("field","",4375,4394);
$z[8][4]['name']="title";
$z[9]=Array("field","",4466,4486);
$z[9][4]['name']="writer";
$z[10]=Array("field","",4510,4562);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("field","",4682,4700);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",4821,4846);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",4901,4927);
$z[13][4]['get']="next";
$z[14]=Array("include","",5170,5207);
$z[14][4]['filename']="footer.htm";

?>