

<li class="m mm7" id="m2">
    <h3><a href="[field:typeurl/]">[field:typename/]</a></h3>
    <ul class="sub" style="display: none;">
        <div class="sn-contain">
            <div class="sn-txt f-l">
                <p class="p-desc">
                    [field:description/] [<a
                        class="yel" href="[field:typeurl/]">查看详情</a>]
                </p>
                <ul class="sn-list2 clearfix">

                </ul>
            </div>
            <div class="sn-pic f-r"><a href="/anli/"><img src="[field:seotitle/]" width="135"
                                                          height="155"></a></div>
        </div>

    </ul>


</li>
