<?php
$z[0]=Array("global","",1150,1176);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",1220,1244);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("channel","\r\n                <a href=\"[field:typeurl/]\" target=\"_blank\" title=\"[field:typename/]\" rel=\"nofollow\">[field:typename/]</a><span class=\"line\"></span>\r\n                ",3691,3910);
$z[2][4]['typeid']="10";
$z[2][4]['type']="son";

?>