<?php
$z[0]=Array("type","[field:typeurl/]",455,505);
$z[0][4]['typeid']="9";
$z[1]=Array("type","[field:typeurl/]",568,618);
$z[1][4]['typeid']="7";
$z[2]=Array("channel","\r\n\r\n<li class=\"m mm7\" id=\"m2\">\r\n    <h3><a href=\"[field:typeurl/]\">[field:typename/]</a></h3>\r\n    <ul class=\"sub\" style=\"display: none;\">\r\n        <div class=\"sn-contain\">\r\n            <div class=\"sn-txt f-l\">\r\n                <p class=\"p-desc\">\r\n                    [field:description/] [<a\r\n                        class=\"yel\" href=\"[field:typeurl/]\">查看详情</a>]\r\n                </p>\r\n                <ul class=\"sn-list2 clearfix\">\r\n\r\n                </ul>\r\n            </div>\r\n            <div class=\"sn-pic f-r\"><a href=\"/anli/\"><img src=\"[field:seotitle/]\" width=\"135\"\r\n                                                          height=\"155\"></a></div>\r\n        </div>\r\n\r\n    </ul>\r\n\r\n\r\n</li>\r\n",3045,4241);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='m mm7 on'><h3><a href='~typelink~' ~rel~>~typename~</a></h3></li><ul class='sub' style='display: none;'><div class='sn-contain'> <div class='sn-txt f-l'><p class='p-desc'>~description~[<a class='yel' href='~typelink~'>查看详情</a>]</p><ul class='sn-list2 clearfix'></ul></div><div class='sn-pic f-r'><a href='[field:typeurl/]'><img src='[field:seotitle/]' width='135' height='155'></a></div></div></ul></li>";

?>