<?php
$z[0]=Array("field","",262,281);
$z[0][4]['name']="title";
$z[1]=Array("global","",282,308);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",353,382);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",426,484);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",881,916);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1246,1275);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n                        <li><a href=\"[field:arcurl/]\"><i><img src=\"[field:litpic/]\" /></i><p><b>[field:title/]</b></p></a></li>\r\n                        ",1499,1691);
$z[6][4]['pagesize']="20";
$z[7]=Array("pagelist","",1933,2011);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2225,2262);
$z[8][4]['filename']="footer.htm";

?>