<?php
$z[0]=Array("field","",262,281);
$z[0][4]['name']="title";
$z[1]=Array("global","",282,308);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",353,382);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",426,484);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",785,820);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1274,1303);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n\r\n    <div class=\"main_left_yanban_box\">\r\n        <div class=\"pic\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"225\" ></a></div>\r\n        <div class=\"title\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></div>\r\n        <div class=\"hangye\"><a href=\"[field:pc/]\" target=\"_blank\">PC站演示</a> &nbsp;&nbsp;&nbsp;&nbsp; <a href=\"[field:mobile/]\" target=\"_blank\">手机微信站演示</a></div>\r\n        <div class=\"bianhao\">样版编号：<span>[field:shorttitle/]</span></div>\r\n        <div class=\"yanshi\"></div>\r\n    </div>\r\n    ",1453,2120);
$z[6][4]['pagesize']="40";
$z[7]=Array("include","",2239,2276);
$z[7][4]['filename']="footer.htm";

?>